version: '3.3'

services:
  db-usco:
    image: postgres:13
    environment:
      - POSTGRES_DB=smart_volley
      - POSTGRES_USER=andres
      - POSTGRES_PASSWORD=andres.22
    ports:
      - 5431:5432
    volumes:
     - ./postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - 5050:80
